language: java
before_install: ./gradlew echoGroupAndVersion
install: ./gradlew clean assemble
script: ./gradlew test
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./gradlew publishArtifactsFromCI
