language: java
before_install:
  - ./gradlew clean
  - ./gradlew echoGroupAndVersion
install: ./gradlew assemble # clean was called in before_install
script: ./gradlew test
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./gradlew publishArtifactsFromCI
