vent:
  pageOptimization:
#    how many workers should pool used for optimization contain?; todo: unused yet
    threads: 4
    full:
      schedule: 0 0 0/1 ? * * *
      crowding: -1
    partial:
      schedule: 0 0/15 * ? * * *
      olderThan:
        value: 12
#       unit should be name of java.time.temporal.ChronoUnit value
        unit: HOURS
#     number of events that need to be present in object to trigger optimization
      crowding: 100

#todo: add weights to operations to control crowding